### ISSUE TITLE
Propuesta de Banner

### ISSUE THREAD

**Issue by NicolasCH19** [udmath/udmath.github.io#2]
Cambiar nombre "semilleros" por investigación, ya que pues según lo hablado serán presentados trabajos de voluntarios que no necesariamente pertenezcan a algún semillero. 
 
Escudo de la universidad, colocar imagen sin fondo.

Eliminar del banner "Horarios". El banner debería ser para temas preponderantes, "horarios" es más una subcategoría de algo.

¿Qué tal dejar solo Noticias y que de ahí salga una lista en la que se encuentre "Periódico UDmath"?

**Comment by wilches** [comment]
No se si con el escudo de la universidad se refiere a solo el logo del header; de ser ese, no habria problema en dejarlo con fondo blanco. Quitarle el fondo a la imagen seria complicado, al menos que alguno supiera manejar un programa como photoshop. 
Ahora, la vista de movil si se ve muy mal:
![image](https://user-images.githubusercontent.com/9202033/53548716-3531b680-3b00-11e9-8b2b-72dc9d8d5c50.png)
Podriamos cambiar el color del header a blanco y ya estaria.
